### ISSUE TITLE
Wrong case for json options

### ISSUE THREAD

**Issue by codebien** [grafana/xk6-output-kafka#13]
We are using camelCase for the json [options](https://github.com/grafana/k6/blob/fc5dfedb7c4871b6d1527cbc97e79dffeee2721d/output/statsd/config.go#L39-L41) in k6 core outputs, ideally, we should use the same in this project to be consistent.

The suggestion is to check the [Config](https://github.com/grafana/xk6-output-kafka/blob/5dcf974ce2b597dedf429a6be6414fda0c087ecb/pkg/kafka/config.go#L38) fields and fix the [current options](https://github.com/grafana/xk6-output-kafka/blob/5dcf974ce2b597dedf429a6be6414fda0c087ecb/pkg/kafka/config.go#L48) with the wrong case.

**Comment by MStoykov** [comment]
I also think that the "argline" ones should be camelCase as well - they are somewhat mostly so in k6 internally already although there are some ... exceptions ... that proves the rule :P
